const themeImages = document.querySelectorAll(".titleAndTheme__theme"),
  body = document.querySelector("body"),
  inputContainer = document.querySelector(".inputSquare"),
  input = document.querySelector(".inputSquare__input"),
  tasksListElement = document.querySelector(".tasks"),
  navigation = document.querySelector(".navigation"),
  marks = () => document.querySelectorAll(".inputSquare__check"),
  getDeleteIcons = () => document.querySelectorAll(".TasksSquare__task--remove"),
  getEveryTask = () => document.querySelectorAll(".TasksSquare__task "),
  allButton = document.querySelector(".navigation__mainButtons--button-all"),
  activeButton = document.querySelector(".navigation__mainButtons--button-active"),
  completedButton = document.querySelector(".navigation__mainButtons--button-completed"),
  getUnCheckedTasks = () => document.querySelectorAll(".TasksSquare__unchecked"),
  numberOfTasksSpan = document.querySelector(".number-of-tasks"),
  clearButton = document.querySelector(".navigation__clearButton"),
  completedTitle = document.querySelector(".completed"),
  activeTitle = document.querySelector(".active");

export {
  themeImages,
  body,
  input,
  tasksListElement,
  navigation,
  marks,
  inputContainer,
  getDeleteIcons,
  getEveryTask,
  allButton,
  activeButton,
  completedButton,
  getUnCheckedTasks,
  numberOfTasksSpan,
  clearButton,
  completedTitle,
  activeTitle,
};
